### ISSUE TITLE
Manage org.osgi:org.osgi.service.condition:1.0.0

### ISSUE THREAD

**Issue by kwin** [wcm-io/io.wcm.maven.aem-cloud-dependencies#63]
AEMaaCS exports package `org.osgi.service.condition` in version `1.0.0` via the system bundle (as it is part of Felix 7.x).
Therefore please manage the following dependency:

```
<dependency>
  <groupId>org.osgi</groupId>
  <artifactId>org.osgi.service.condition</artifactId>
  <version>1.0.0</version>
</dependency>
```

which refers to the [OSGi Condition Service Specification](https://docs.osgi.org/specification/osgi.core/8.0.0/service.condition.html)

**Comment by stefanseifert** [comment]
done with #64

**Comment by kwin** [comment]
Thanks a lot for the quick fix @stefanseifert!
